Pointer: Pointer.o
	g++ -g Pointer.o -o Pointer.exe
	
Pointer.o: Pointer.cpp
	g++ -std=c++0x -g -c -w Pointer.cpp

Maximum: Maximum.o
	g++ -g Maximum.o -o Maximum.exe
	
Maximum.o: Maximum.cpp
	g++ -std=c++0x -g -c -w Maximum.cpp

Rectangle: Rectangle.o
	g++ -g Rectangle.o -o Rectangle.exe
	
Rectangle.o: Rectangle.cpp Rectangle.h
	g++ -std=c++0x -g -c -w Rectangle.cpp

Surcharge: Surcharge.o
	g++ -g Surcharge.o -o Surcharge.exe
	
Surcharge.o: Surcharge.cpp 
	g++ -std=c++0x -g -c -w Surcharge.cpp

Iterator: Iterator.o
	g++ -g Iterator.o -o Iterator.exe
	
Iterator.o: Iterator.cpp 
	g++ -std=c++0x -g -c -w Iterator.cpp

Destructeur: Destructeur.o
	g++ -g Destructeur.o -o Destructeur.exe
	
Destructeur.o: Destructeur.cpp 
	g++ -std=c++0x -g -c -w Destructeur.cpp

ConstructorParDefault: ConstructorParDefault.o
	g++ -g ConstructorParDefault.o -o ConstructorParDefault.exe
	
ConstructorParDefault.o: ConstructorParDefault.cpp 
	g++ -std=c++0x -g -c -w ConstructorParDefault.cpp

Exercice0: Exercice0.o
	g++ -g Exercice0.o -o Exercice0.exe
	
Exercice0.o: Exercice0.cpp 
	g++ -std=c++0x -g -c -w Exercice0.cpp

Heritage: Heritage.o
	g++ -g Heritage.o -o Heritage.exe
	
Heritage.o: Heritage.cpp 
	g++ -std=c++0x -g -c -w Heritage.cpp

Exercice1: Exercice1.o
	g++ -g Exercice1.o -o Exercice1.exe
	
Exercice1.o: Exercice1.cpp 
	g++ -std=c++0x -g -c -w Exercice1.cpp

ObjetCommeUnAttribut: ObjetCommeUnAttribut.o
	g++ -g ObjetCommeUnAttribut.o -o ObjetCommeUnAttribut.exe
	
ObjetCommeUnAttribut.o: ObjetCommeUnAttribut.cpp 
	g++ -std=c++0x -g -c -w ObjetCommeUnAttribut.cpp

JeuMorpion: JeuMorpion.o
	g++ -g JeuMorpion.o -o JeuMorpion.exe
	
JeuMorpion.o: JeuMorpion.cpp JeuMorpion.h
	g++ -std=c++0x -g -c -w JeuMorpion.cpp

Template: Template.o
	g++ -g Template.o -o Template.exe

Template.o: Template.cpp 
	g++ -std=c++0x -g -c -w Template.cpp
	
TableauDyn.o: TableauDyn.cpp 
	g++ -std=c++0x -g -c -w TableauDyn.cpp

TableauDyn: TableauDyn.o
	g++ -g Template.o -o TableauDyn.exe
	

Ensemble: Ensemble.o Animal.o
	g++ -g Ensemble.o Animal.o -o Ensemble.exe

Ensemble.o: Ensemble.cpp 
	g++ -std=c++0x -g -c -w Ensemble.cpp

Animal.o: Animal.cpp Animal.h
	g++ -std=c++0x -g -c -w Animal.cpp

assert.o: assert.cpp 
	g++ -std=c++0x -g -c -w assert.cpp

assert: assert.o
	g++ -g assert.o -o assert.exe

Continue.o: Continue.cpp 
	g++ -std=c++0x -g -c -w Continue.cpp

Continue: Continue.o
	g++ -g Continue.o -o Continue.exe

Lambda: Lambda.o
	g++ -g Lambda.o -o Lambda.exe

Lambda.o: Lambda.cpp 
	g++ -std=c++0x -g -c -w Lambda.cpp

priority_queue: priority_queue.o
	g++ -g priority_queue.o -o priority_queue.exe

priority_queue.o: priority_queue.cpp 
	g++ -std=c++0x -g -c -w priority_queue.cpp

Container: Container.o
	g++ -g Container.o -o Container.exe

Container.o: Container.cpp 
	g++ -std=c++0x -g -c -w Container.cpp

Sort: Sort.o
	g++ -g Sort.o -o Sort.exe

Sort.o: Sort.cpp 
	g++ -std=c++0x -g -c -w Sort.cpp

Febonacci: Febonacci.o
	g++ -g Febonacci.o -o Febonacci.exe

Febonacci.o: Febonacci.cpp 
	g++ -std=c++0x -g -c -w Febonacci.cpp

StringReverse: StringReverse.o
	g++ -g StringReverse.o -o StringReverse.exe

StringReverse.o: StringReverse.cpp 
	g++ -std=c++0x -g -c -w StringReverse.cpp

clean: 
	rm -f *.o *.exe