clean: 
	rm -f *.o *.exe
	
Algorithm: Algorithm.o
	g++ -g Algorithm.o -o Algorithm.exe

Algorithm.o: Algorithm.cpp 
	g++ -std=c++0x -g -c -w Algorithm.cpp

BinarySearch: BinarySearch.o
	g++ -g BinarySearch.o -o BinarySearch.exe

BinarySearch.o: BinarySearch.cpp 
	g++ -std=c++0x -g -c -w BinarySearch.cpp