clean: 
	rm -f *.o *.exe
	
Exercice1: Exercice1.o
	g++ -g Exercice1.o -o Exercice1.exe

Exercice1.o: Exercice1.cpp 
	g++ -std=c++0x -g -c -w Exercice1.cpp
	
Statistiques: Statistiques.o
	g++ -g Statistiques.o -o Statistiques.exe

Statistiques.o: Statistiques.cpp 
	g++ -std=c++0x -g -c -w Statistiques.cpp