Iterator: Iterator.o
	g++ -g Iterator.o -o Iterator.exe
	
Iterator.o: Iterator.cpp 
	g++ -std=c++0x -g -c -w Iterator.cpp

priority_queue: priority_queue.o
	g++ -g priority_queue.o -o priority_queue.exe

priority_queue.o: priority_queue.cpp 
	g++ -std=c++0x -g -c -w priority_queue.cpp

Container: Container.o
	g++ -g Container.o -o Container.exe

Container.o: Container.cpp 
	g++ -std=c++0x -g -c -w Container.cpp

Sort: Sort.o
	g++ -g Sort.o -o Sort.exe

Sort.o: Sort.cpp 
	g++ -std=c++0x -g -c -w Sort.cpp
	
Set: Set.o
	g++ -g Set.o -o Set.exe

Set.o: Set.cpp 
	g++ -std=c++0x -g -c -w Set.cpp
	
MultiSet: MultiSet.o
	g++ -g MultiSet.o -o MultiSet.exe

MultiSet.o: MultiSet.cpp 
	g++ -std=c++0x -g -c -w MultiSet.cpp

Map: Map.o
	g++ -g Map.o -o Map.exe

Map.o: Map.cpp 
	g++ -std=c++0x -g -c -w Map.cpp

MultiMap: MultiMap.o
	g++ -g MultiMap.o -o MultiMap.exe

MultiMap.o: MultiMap.cpp 
	g++ -std=c++0x -g -c -w MultiMap.cpp

Vector: Vector.o
	g++ -g Vector.o -o Vector.exe

Vector.o: Vector.cpp 
	g++ -std=c++0x -g -c -w Vector.cpp

Deque: Deque.o
	g++ -g Deque.o -o Deque.exe

Deque.o: Deque.cpp 
	g++ -std=c++0x -g -c -w Deque.cpp

Queue: Queue.o
	g++ -g Queue.o -o Queue.exe

Queue.o: Queue.cpp 
	g++ -std=c++0x -g -c -w Queue.cpp

List: List.o
	g++ -g List.o -o List.exe

List.o: List.cpp 
	g++ -std=c++0x -g -c -w List.cpp

Stack: Stack.o
	g++ -g Stack.o -o Stack.exe

Stack.o: Stack.cpp 
	g++ -std=c++0x -g -c -w Stack.cpp
	
IterateurPourListetPourVector: IterateurPourListetPourVector.o
	g++ -g IterateurPourListetPourVector.o -o IterateurPourListetPourVector.exe

IterateurPourListetPourVector.o: IterateurPourListetPourVector.cpp 
	g++ -std=c++0x -g -c -w IterateurPourListetPourVector.cpp

String: String.o
	g++ -g String.o -o String.exe

String.o: String.cpp 
	g++ -std=c++0x -g -c -w String.cpp

TimerInsertion: TimerInsertion.o
	g++ -g TimerInsertion.o -o TimerInsertion.exe

TimerInsertion.o: TimerInsertion.cpp 
	g++ -std=c++0x -g -c -w TimerInsertion.cpp

clean: 
	rm -f *.o *.exe